language: python
python:
- '3.6'
script:
- python mapbuild/pybuild.py
install:
- pip install -r mapbuild/requirements.txt
after_script:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- git checkout -b ${TRAVIS_BUILD_NUMBER}
- git add .
- git commit -m "travis update [skip ci]"
- git push origin HEAD:${TRAVIS_BUILD_NUMBER}
env:
  global:
  - secure: Lr/2B5nH2nKXlVvlnn9WHyH6gXbNvSDIn1dfUt1UWCuUFWuHZq1/fExbsEEW8MXC6IbjrHJEiqWfbaLM2s3iBX/h9bKWi+dCS2nBGpHthYQ3WEbtD2AziieTg1+u4zdeqUpPiPatBX6ctZvd66KlStYybx4rkfPWb+aXPI7stFA1Q/Ozc3B5AtDUQugrJkHJEh4uJXEWDCRlEM3WexN57H9kjIklHEqe1A6EbnGJKnv3j13gJXac3Fe9buVAaPojEoxcUOgobt6j5+LDIDtcNC+IG8ZoySfbiFnWmDKoJqo7GqLRCyXFZZ0BkwyI8V2zQ22e/xZoeooKVCsbEMyssW1yoPfK1iWnLl5mxB+DvCWwn3oVsvMYX9tUrRtvsq3w0Wyw2k8CI+7xDIRTmdm1gRly4ghhUCRDTydOg6GqXKuRsN4+yRUyGtY1ZIeqBuaydxdk/JDFz+kmn+pqRQ7oSPTRIEILqQNM/8wpKGfV9jCwEyBlbRpjWeIT2iY7NoL6/4q9ahic/SStj7rUsEmhsQR5b6v2gbJhxy5sbNS5kHgFU4DghWj8CA6eFM4clwq4CX5EtEEVTKhibttU3QEbSv59OyquwxfT0e+EThFLdnTbXQ3bIAhs6GnIwHQ728CUogIYsP6q/riZQkQvoXJ63TPC2f8bJ0hbbbHvCdJUitQ=
