language: python
python:
- '3.6'
script:
- python mapbuild/pybuild.py

install:
  - pip install -r mapbuild/requirements.txt

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  file: "docs/digitallifecollective.json"
  keep-history: true
  on:
    branch: development