language: python
python:
- '3.6'
script:
- python mapbuild/pybuild.py
install:
- pip install -r mapbuild/requirements.txt

after_script:
  - git checkout -b ${TRAVIS_BUILD_NUMBER}
  - git add .
  - git commit -m "travis update ${TRAVIS_BUILD_NUMBER} [skip ci]"
  - git push origin HEAD:${TRAVIS_BUILD_NUMBER}


