language: python
python:
- '3.6'
script:
- python mapbuild/pybuild.py

install:
  - pip install -r mapbuild/requirements.txt

after_success:
  - git add .
  - git commit --message "Travis build"
  - git push origin HEAD:development